// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SttbApi.Data;

#nullable disable

namespace SttbApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312074812_AddAdmin")]
    partial class AddAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SttbApi.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("SttbApi.Models.Berita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Beritas");
                });

            modelBuilder.Entity("SttbApi.Models.CompetencyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProgramStudiId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramStudiId");

                    b.ToTable("CompetencyGroups");
                });

            modelBuilder.Entity("SttbApi.Models.CompetencyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetencyGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyGroupId");

                    b.ToTable("CompetencyItems");
                });

            modelBuilder.Entity("SttbApi.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("CurriculumGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumGroupId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SttbApi.Models.CurriculumGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramStudiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramStudiId");

                    b.ToTable("CurriculumGroups");
                });

            modelBuilder.Entity("SttbApi.Models.MataKuliah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramStudiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramStudiId");

                    b.ToTable("MataKuliah");
                });

            modelBuilder.Entity("SttbApi.Models.OverviewAbout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProgramStudiId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramStudiId");

                    b.ToTable("OverviewAbouts");
                });

            modelBuilder.Entity("SttbApi.Models.OverviewRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProgramStudiId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramStudiId");

                    b.ToTable("OverviewRequirements");
                });

            modelBuilder.Entity("SttbApi.Models.ProgramStudi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroSubtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Highlights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalCredits")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProgramStudi");
                });

            modelBuilder.Entity("SttbApi.Models.CompetencyGroup", b =>
                {
                    b.HasOne("SttbApi.Models.ProgramStudi", "ProgramStudi")
                        .WithMany("Competencies")
                        .HasForeignKey("ProgramStudiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramStudi");
                });

            modelBuilder.Entity("SttbApi.Models.CompetencyItem", b =>
                {
                    b.HasOne("SttbApi.Models.CompetencyGroup", "CompetencyGroup")
                        .WithMany("Items")
                        .HasForeignKey("CompetencyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetencyGroup");
                });

            modelBuilder.Entity("SttbApi.Models.Course", b =>
                {
                    b.HasOne("SttbApi.Models.CurriculumGroup", "CurriculumGroup")
                        .WithMany("Courses")
                        .HasForeignKey("CurriculumGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumGroup");
                });

            modelBuilder.Entity("SttbApi.Models.CurriculumGroup", b =>
                {
                    b.HasOne("SttbApi.Models.ProgramStudi", "ProgramStudi")
                        .WithMany("Curriculum")
                        .HasForeignKey("ProgramStudiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramStudi");
                });

            modelBuilder.Entity("SttbApi.Models.MataKuliah", b =>
                {
                    b.HasOne("SttbApi.Models.ProgramStudi", "ProgramStudi")
                        .WithMany("MataKuliah")
                        .HasForeignKey("ProgramStudiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramStudi");
                });

            modelBuilder.Entity("SttbApi.Models.OverviewAbout", b =>
                {
                    b.HasOne("SttbApi.Models.ProgramStudi", "ProgramStudi")
                        .WithMany("Abouts")
                        .HasForeignKey("ProgramStudiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramStudi");
                });

            modelBuilder.Entity("SttbApi.Models.OverviewRequirement", b =>
                {
                    b.HasOne("SttbApi.Models.ProgramStudi", "ProgramStudi")
                        .WithMany("Requirements")
                        .HasForeignKey("ProgramStudiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramStudi");
                });

            modelBuilder.Entity("SttbApi.Models.CompetencyGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SttbApi.Models.CurriculumGroup", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("SttbApi.Models.ProgramStudi", b =>
                {
                    b.Navigation("Abouts");

                    b.Navigation("Competencies");

                    b.Navigation("Curriculum");

                    b.Navigation("MataKuliah");

                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
